name: Auto‑update & Build HopToDesk Flatpak

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  update-manifest:
    name: 🚀 Check for new HopToDesk release
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      sha:     ${{ steps.vars.outputs.sha256 }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest HopToDesk .deb
        run: |
          curl -L -o hoptodesk.deb https://www.hoptodesk.com/hoptodesk.deb

      - name: Extract version & SHA256
        id: vars
        run: |
          VERSION=$(dpkg-deb -f hoptodesk.deb Version | cut -d'-' -f1)
          SHA256=$(sha256sum hoptodesk.deb | cut -d' ' -f1)
          echo "version=$VERSION"     >> $GITHUB_OUTPUT
          echo "sha256=$SHA256"       >> $GITHUB_OUTPUT

      - name: Bump only the HopToDesk .deb URL & checksum
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          NEW_SHA="${{ steps.vars.outputs.sha256 }}"

          # 1) Update the .deb URL to the new version
          sed -i -E \
            "s#(https://www.hoptodesk.com/hoptodesk-)[0-9]+\.[0-9]+\.[0-9]+(-0-x86_64\.deb)#\1${VERSION}\2#" \
            com.hoptodesk.HopToDesk.json

          # 2) Immediately after that URL, update only its sha256
          sed -i -E "/hoptodesk-${VERSION}-0-x86_64\\.deb\"/{n;s#\"sha256\": \"[0-9a-f]+\"#\"sha256\": \"${NEW_SHA}\"#;}" \
            com.hoptodesk.HopToDesk.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-hoptodesk-${{ steps.vars.outputs.version }}
          title: "Update HopToDesk to v${{ steps.vars.outputs.version }}"
          body: |
            Automated update of HopToDesk Flatpak manifest to version **${{ steps.vars.outputs.version }}**.
          labels: automated-update

  build-flatpak:
    name: 🧪 Validate Flatpak build
    needs: update-manifest
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: x86_64
            distro: ubuntu18.04
          - arch: x86_64
            distro: ubuntu20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for multi‑arch
        uses: docker/setup-qemu-action@v2

      - name: Build HopToDesk Flatpak on ${{ matrix.arch }} / ${{ matrix.distro }}
        uses: rustdesk-org/run-on-arch-action@amd64-support
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            set -eux
            apt-get update
            DEBIAN_FRONTEND=noninteractive \
              apt-get install -y --no-install-recommends \
                ca-certificates \
                git \
                flatpak \
                flatpak-builder
            update-ca-certificates
            rm -rf /var/lib/apt/lists/*
          run: |
            set -eux

            # fresh clone of shared-modules
            rm -rf shared-modules
            git clone https://github.com/flathub/shared-modules.git --depth=1

            # add Flathub in user mode
            flatpak --user remote-add --if-not-exists flathub \
              https://dl.flathub.org/repo/flathub.flatpakrepo

            # build the manifest
            flatpak-builder \
              --force-clean \
              --install-deps-from=flathub \
              --user \
              --repo=repo \
              build-dir \
              com.hoptodesk.HopToDesk.json
