name: Update HopToDesk Flatpak

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 03:00 UTC (adjust as needed)
  workflow_dispatch:      # Manual trigger
  pull_request:

jobs:
  update-flatpak:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Flathub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies: flatpak and flatpak-builder, plus jq and wget for processing.
      - name: Install dependencies
        run: |
          # Wait for dpkg lock to be released (if held by another process)
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for dpkg lock to be released..."
            sleep 1
          done
          sudo bash -c 'apt-get update && apt-get -y install flatpak flatpak-builder jq wget'

      # Add Flathub remote in user mode.
      - name: Add Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      # Download the latest HopToDesk deb package from its working URL.
      - name: Download latest HopToDesk deb package
        run: |
          wget -O hoptodesk.deb "https://www.hoptodesk.com/hoptodesk.deb"

      # Compute the SHA256 checksum of the downloaded deb file.
      - name: Compute SHA256 of HopToDesk deb
        id: compute_sha
        run: |
          SHA256=$(sha256sum hoptodesk.deb | cut -d' ' -f1)
          echo "Computed SHA256: $SHA256"
          echo "HOPTO_SHA256=$SHA256" >> $GITHUB_ENV

      # Extract the package version from the deb metadata.
      - name: Extract version from deb package
        id: extract_version
        run: |
          ver=$(dpkg-deb --field hoptodesk.deb Version | tr -d '\n')
          echo "Extracted version: $ver"
          echo "HOPTO_VERSION=$ver" >> $GITHUB_ENV

      # Update the Flatpak manifest (com.hoptodesk.HopToDesk.json):
      #  • Set the top-level version.
      #  • Update the SHA256 for the deb source.
      # (If needed, you can also adjust build-commands here.)
      - name: Update Flatpak manifest (com.hoptodesk.HopToDesk.json)
        run: |
          jq --arg ver "$HOPTO_VERSION" \
             --arg sha "$HOPTO_SHA256" \
             '(.version) = $ver |
              (.modules[] |= 
                (if type=="object" then
                   (if .sources then
                      .sources |= map(
                        if .url == "https://www.hoptodesk.com/hoptodesk.deb" then .sha256 = $sha else . end
                      )
                    else . end)
                 else .
                 end)
              )' com.hoptodesk.HopToDesk.json > tmp_manifest.json && mv tmp_manifest.json com.hoptodesk.HopToDesk.json

      # Build the Flatpak using the official command.
      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.hoptodesk.HopToDesk.json

      # Export the Flatpak bundle.
      - name: Export Flatpak bundle
        run: |
          flatpak build-bundle repo hoptodesk.flatpak com.hoptodesk.HopToDesk --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      # Optionally, create a pull request with the updated manifest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "update/hoptodesk-${{ env.HOPTO_VERSION }}"
          base: main
          title: "Update HopToDesk to v${{ env.HOPTO_VERSION }}"
          body: "This PR updates the HopToDesk Flatpak manifest to version ${{ env.HOPTO_VERSION }} and updates the SHA256 checksum for the deb package."
          commit-message: "Update HopToDesk to v${{ env.HOPTO_VERSION }}"
          labels: automation
          token: ${{ secrets.FLATHUB_BOT_TOKEN || github.token }}
