name: Auto‑update & Build HopToDesk Flatpak

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      sha:     ${{ steps.vars.outputs.sha256 }}
    steps:
      - uses: actions/checkout@v3

      - name: Download latest HopToDesk .deb
        run: curl -L -o hoptodesk.deb https://www.hoptodesk.com/hoptodesk.deb
        
      - name: Extract version & SHA256
        id: vars
        run: |
          VERSION=$(dpkg-deb -f hoptodesk.deb Version | cut -d'-' -f1)
          SHA256=$(sha256sum hoptodesk.deb | cut -d' ' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "sha256=$SHA256"   >> $GITHUB_OUTPUT

      - name: Bump dest-filename & sha256 in manifest
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          SHA="${{ steps.vars.outputs.sha256 }}"

          sed -i -E \
            "/dest-filename\": \"hoptodesk-${VERSION}-0-x86_64.deb\"/{n;s#\"sha256\": \"[0-9a-f]+\"#\"sha256\": \"${SHA}\"#;}" \
            com.hoptodesk.HopToDesk.json

      - name: Get default branch
        id: default-branch
        run: echo "branch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-hoptodesk-${{ steps.vars.outputs.version }}
          base: ${{ steps.default-branch.outputs.branch }}

  # Removed duplicate build-flatpak job definition

  build-flatpak:
    needs: update-manifest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            distro: ubuntu20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2

      - name: Build Flatpak on ${{ matrix.arch }} / ${{ matrix.distro }}
        uses: rustdesk-org/run-on-arch-action@amd64-support
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            set -eux
            apt-get update
            DEBIAN_FRONTEND=noninteractive \
              apt-get install -y --no-install-recommends \
                ca-certificates \
                git \
                flatpak \
                flatpak-builder \
                patch \
                elfutils \
                xz-utils \
                librsvg2-common
            update-ca-certificates
            rm -rf /var/lib/apt/lists/*
          run: |
            set -eux
            rm -rf shared-modules
            git clone https://github.com/flathub/shared-modules.git --depth=1
            flatpak --user remote-add --if-not-exists flathub \
              https://dl.flathub.org/repo/flathub.flatpakrepo
            flatpak-builder \
              --force-clean \
              --install-deps-from=flathub \
              --user \
              --repo=repo \
              build-dir \
              com.hoptodesk.HopToDesk.json
      
      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v4
        with:
          name: hoptodesk-${{ matrix.arch }}
          path: ./hoptodesk-${{ matrix.arch }}.flatpak

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hoptodesk-${{ matrix.arch }}.flatpak
          asset_name: hoptodesk-${{ matrix.arch }}.flatpak
          tag: ${{ github.ref }}
